
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: fabricio
  password: luvi@1904

development:
  <<: *default
  database: app_municipe_development

test:
  <<: *default
  database: app_municipe_test

production:
  <<: *default
  database: app_municipe_production
  username: app_municipe
  password: <%= ENV['APP_MUNICIPE_DATABASE_PASSWORD'] %>
